// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "baseUrl": string;
      "model": string;
      "maxTokens": number;
      "temperature": string;
      "systemPrompt": string;
      "username": string;
      "loginPassword": string;
      "userId": number;
      "userQuotaJson": string;
      "paperchatModelsCache": string;
      "paperchatRatiosCache": string;
      "uploadRawPdfOnFailure": boolean;
      "panelMode": string;
      "firstInstalledVersion": string;
      "guideStatus": number;
      "contextMaxRecentPairs": number;
      "contextEnableSummary": boolean;
      "contextSummaryThreshold": number;
      "enableAIWriteOperations": boolean;
      "enableSemanticSearch": boolean;
    };
  }
}
