// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "baseUrl": string;
      "model": string;
      "maxTokens": number;
      "temperature": string;
      "systemPrompt": string;
      "username": string;
      "loginPassword": string;
      "userId": number;
      "userQuotaJson": string;
      "userSubscriptionJson": string;
      "paperchatModelsCache": string;
      "paperchatRatiosCache": string;
      "paperchatRoutingConfigCache": string;
      "paperchatTierState": string;
      "paperchatSuppressHighTierWarning": boolean;
      "uploadRawPdfOnFailure": boolean;
      "panelMode": string;
      "debugContextExportEnabled": boolean;
      "firstInstalledVersion": string;
      "guideStatus": number;
      "contextMaxRecentPairs": number;
      "contextEnableSummary": boolean;
      "contextAutoCompactBufferTokens": number;
      "contextAutoCompactWindowTokens": number;
      "toolPermissionDefaultModes": string;
      "webSearchProvider": string;
      "agentMaxPlanningIterations": number;
    };
  }
}
