export const BUILT_IN_PAPER_SKILL_MARKDOWN: Record<string, string> = {
  "paper-deep-reading": [
    "---",
    "name: Paper Deep Reading",
    "description: Read one paper deeply by separating claims, evidence, assumptions, and limits.",
    "triggers:",
    "  - deep reading",
    "  - close reading",
    "  - summarize paper",
    "  - paper summary",
    "  - 精读",
    "  - 总结论文",
    "  - 读论文",
    "---",
    "",
    "Use this workflow when the user wants to understand a single paper.",
    "",
    "1. Identify the paper's core question, main contribution, and claimed novelty.",
    "2. Extract the method, data, experiments, baselines, metrics, and evaluation setup.",
    "3. Tie each important claim to concrete evidence in the paper. If the evidence is missing or weak, say so.",
    "4. Separate what the authors proved from what they implied or speculated.",
    "5. Explain the result in practical terms: when this idea works, when it might fail, and who would care.",
    "6. End with 3-5 high-value follow-up questions the user can ask next.",
    "",
    "Do not flatten the paper into a generic abstract. Preserve section-level evidence and cite the source section, figure, table, or annotation when available.",
  ].join("\n"),

  "related-work-map": [
    "---",
    "name: Related Work Map",
    "description: Build a map of adjacent papers, competing methods, and research gaps.",
    "triggers:",
    "  - related work",
    "  - literature review",
    "  - compare papers",
    "  - research gap",
    "  - 相关工作",
    "  - 文献综述",
    "  - 对比论文",
    "---",
    "",
    "Use this workflow when the user compares papers or prepares related work.",
    "",
    "1. Start from the target paper's problem, method family, task, dataset, and claimed contribution.",
    "2. Group neighboring papers by role: predecessor, direct competitor, complementary method, evaluation benchmark, and application paper.",
    "3. For each group, compare assumptions, inputs, outputs, supervision, datasets, metrics, and failure modes.",
    "4. Identify the real gap with evidence. Avoid claiming novelty just because wording differs.",
    "5. Produce a compact map: paper or group, relationship to target paper, strongest evidence, and what to read next.",
    "",
    "When sources disagree, keep the disagreement visible instead of merging it into one smooth story.",
  ].join("\n"),

  "claim-evidence-audit": [
    "---",
    "name: Claim Evidence Audit",
    "description: Check whether a paper's claims are actually supported by its experiments, figures, and citations.",
    "triggers:",
    "  - claim evidence",
    "  - evidence audit",
    "  - verify claim",
    "  - check conclusion",
    "  - 证据",
    "  - 结论可靠吗",
    "  - 是否支持",
    "---",
    "",
    "Use this workflow when the user asks whether a paper is convincing.",
    "",
    "1. List the major claims in the abstract, introduction, and conclusion.",
    "2. For each claim, find the strongest supporting experiment, theorem, ablation, figure, table, or cited source.",
    "3. Mark claims as supported, partially supported, unsupported, or not checked yet.",
    "4. Watch for common paper failure modes: missing baselines, cherry-picked datasets, weak ablations, metric mismatch, small samples, leakage, and conclusions that outrun results.",
    "5. Explain what extra evidence would change the confidence level.",
    "",
    "Be fair. A narrow claim supported by narrow evidence is fine; the problem is when the claim is broader than the evidence.",
  ].join("\n"),

  "method-reproduction-plan": [
    "---",
    "name: Method Reproduction Plan",
    "description: Turn a method section into a practical reproduction or implementation checklist.",
    "triggers:",
    "  - reproduce",
    "  - reproduction",
    "  - implement method",
    "  - replication",
    "  - 复现",
    "  - 实现方法",
    "  - 代码实现",
    "---",
    "",
    "Use this workflow when the user wants to reproduce, implement, or evaluate a paper's method.",
    "",
    "1. Extract the minimum runnable pipeline: inputs, preprocessing, model or algorithm, training or inference steps, outputs, and evaluation.",
    "2. Identify exact hyperparameters, prompts, thresholds, datasets, splits, hardware, and dependencies when the paper provides them.",
    "3. Mark missing details explicitly. Do not invent implementation choices without labeling them as assumptions.",
    "4. Convert the method into a staged plan: smoke test, small-scale reproduction, full evaluation, and sanity checks.",
    "5. Include expected failure points and what logs, metrics, or artifacts would diagnose each one.",
    "",
    "Prefer a practical checklist over prose. The user should be able to start implementation from the answer.",
  ].join("\n"),

  "reviewer-style-critique": [
    "---",
    "name: Reviewer Style Critique",
    "description: Read like a peer reviewer and produce strengths, weaknesses, questions, and decision-relevant risks.",
    "triggers:",
    "  - peer review",
    "  - review this paper",
    "  - critique",
    "  - weaknesses",
    "  - 审稿",
    "  - 批判",
    "  - 缺点",
    "---",
    "",
    "Use this workflow when the user wants a critical assessment of a paper.",
    "",
    "1. Summarize the contribution in one or two sentences before criticizing it.",
    "2. Separate strengths, weaknesses, questions for authors, and threats to validity.",
    "3. Judge novelty, technical soundness, empirical support, clarity, and reproducibility separately.",
    "4. Point to concrete evidence from the paper for each criticism. Avoid vague complaints.",
    "5. End with the highest-leverage fixes: what would most improve the paper or the user's understanding of it.",
    "",
    "Be direct but not performative. The goal is useful judgment, not sounding harsh.",
  ].join("\n"),
};
