export const BUILT_IN_PAPER_SKILL_MARKDOWN: Record<string, string> = {
  "paper-deep-reading": [
    "---",
    "name: Paper Deep Reading",
    "description: Read one paper deeply by separating claims, evidence, assumptions, and limits.",
    "triggers:",
    "  - deep reading",
    "  - close reading",
    "  - summarize paper",
    "  - paper summary",
    "  - 精读",
    "  - 总结论文",
    "  - 读论文",
    "---",
    "",
    "Use this workflow when the user wants to understand a single paper.",
    "",
    "1. Identify the paper's core question, main contribution, and claimed novelty.",
    "2. Extract the method, data, experiments, baselines, metrics, and evaluation setup.",
    "3. Tie each important claim to concrete evidence in the paper. If the evidence is missing or weak, say so.",
    "4. Separate what the authors proved from what they implied or speculated.",
    "5. Explain the result in practical terms: when this idea works, when it might fail, and who would care.",
    "6. End with 3-5 high-value follow-up questions the user can ask next.",
    "",
    "Do not flatten the paper into a generic abstract. Preserve section-level evidence and cite the source section, figure, table, or annotation when available.",
  ].join("\n"),

  "related-work-map": [
    "---",
    "name: Related Work Map",
    "description: Build a map of adjacent papers, competing methods, and research gaps.",
    "triggers:",
    "  - related work",
    "  - literature review",
    "  - compare papers",
    "  - research gap",
    "  - 相关工作",
    "  - 文献综述",
    "  - 对比论文",
    "---",
    "",
    "Use this workflow when the user compares papers or prepares related work.",
    "",
    "1. Start from the target paper's problem, method family, task, dataset, and claimed contribution.",
    "2. Group neighboring papers by role: predecessor, direct competitor, complementary method, evaluation benchmark, and application paper.",
    "3. For each group, compare assumptions, inputs, outputs, supervision, datasets, metrics, and failure modes.",
    "4. Identify the real gap with evidence. Avoid claiming novelty just because wording differs.",
    "5. Produce a compact map: paper or group, relationship to target paper, strongest evidence, and what to read next.",
    "",
    "When sources disagree, keep the disagreement visible instead of merging it into one smooth story.",
  ].join("\n"),

  "claim-evidence-audit": [
    "---",
    "name: Claim Evidence Audit",
    "description: Check whether a paper's claims are actually supported by its experiments, figures, and citations.",
    "triggers:",
    "  - claim evidence",
    "  - evidence audit",
    "  - verify claim",
    "  - check conclusion",
    "  - 证据",
    "  - 结论可靠吗",
    "  - 是否支持",
    "---",
    "",
    "Use this workflow when the user asks whether a paper is convincing.",
    "",
    "1. List the major claims in the abstract, introduction, and conclusion.",
    "2. For each claim, find the strongest supporting experiment, theorem, ablation, figure, table, or cited source.",
    "3. Mark claims as supported, partially supported, unsupported, or not checked yet.",
    "4. Watch for common paper failure modes: missing baselines, cherry-picked datasets, weak ablations, metric mismatch, small samples, leakage, and conclusions that outrun results.",
    "5. Explain what extra evidence would change the confidence level.",
    "",
    "Be fair. A narrow claim supported by narrow evidence is fine; the problem is when the claim is broader than the evidence.",
  ].join("\n"),

  "method-reproduction-plan": [
    "---",
    "name: Method Reproduction Plan",
    "description: Turn a method section into a practical reproduction or implementation checklist.",
    "triggers:",
    "  - reproduce",
    "  - reproduction",
    "  - implement method",
    "  - replication",
    "  - 复现",
    "  - 实现方法",
    "  - 代码实现",
    "---",
    "",
    "Use this workflow when the user wants to reproduce, implement, or evaluate a paper's method.",
    "",
    "1. Extract the minimum runnable pipeline: inputs, preprocessing, model or algorithm, training or inference steps, outputs, and evaluation.",
    "2. Identify exact hyperparameters, prompts, thresholds, datasets, splits, hardware, and dependencies when the paper provides them.",
    "3. Mark missing details explicitly. Do not invent implementation choices without labeling them as assumptions.",
    "4. Convert the method into a staged plan: smoke test, small-scale reproduction, full evaluation, and sanity checks.",
    "5. Include expected failure points and what logs, metrics, or artifacts would diagnose each one.",
    "",
    "Prefer a practical checklist over prose. The user should be able to start implementation from the answer.",
  ].join("\n"),

  "reviewer-style-critique": [
    "---",
    "name: Reviewer Style Critique",
    "description: Read like a peer reviewer and produce strengths, weaknesses, questions, and decision-relevant risks.",
    "triggers:",
    "  - peer review",
    "  - review this paper",
    "  - critique",
    "  - weaknesses",
    "  - 审稿",
    "  - 批判",
    "  - 缺点",
    "---",
    "",
    "Use this workflow when the user wants a critical assessment of a paper.",
    "",
    "1. Summarize the contribution in one or two sentences before criticizing it.",
    "2. Separate strengths, weaknesses, questions for authors, and threats to validity.",
    "3. Judge novelty, technical soundness, empirical support, clarity, and reproducibility separately.",
    "4. Point to concrete evidence from the paper for each criticism. Avoid vague complaints.",
    "5. End with the highest-leverage fixes: what would most improve the paper or the user's understanding of it.",
    "",
    "Be direct but not performative. The goal is useful judgment, not sounding harsh.",
  ].join("\n"),

  "novelty-positioning": [
    "---",
    "name: Novelty Positioning",
    "description: Judge what is genuinely new in a paper and what is inherited from prior work.",
    "triggers:",
    "  - novelty",
    "  - what's new",
    "  - new compared to prior work",
    "  - contribution positioning",
    "  - 创新点",
    "  - 新意",
    "  - 和以前工作相比",
    "---",
    "",
    "Use this workflow when the user asks what is actually new or important about a paper.",
    "",
    "1. Separate the paper into problem framing, method, data, evaluation, and claimed contribution.",
    "2. Identify which pieces are standard, adapted, or likely novel.",
    "3. Compare the claimed novelty against the closest baselines or cited prior work when available.",
    "4. Distinguish between a real methodological change, a packaging change, and an evaluation-only difference.",
    "5. End with a short verdict: what is genuinely new, what is incremental, and what would need verification from neighboring papers.",
    "",
    "Avoid inflated novelty language. A useful incremental paper is still useful; just label it correctly.",
  ].join("\n"),

  "citation-audit": [
    "---",
    "name: Citation Audit",
    "description: Check whether cited papers actually support the surrounding statement or framing.",
    "triggers:",
    "  - citation audit",
    "  - check citation",
    "  - does this reference support",
    "  - verify reference",
    "  - 引用是否支持",
    "  - 检查引用",
    "  - 这个引用",
    "  - 支持作者这里的说法",
    "  - 支持这句话",
    "  - 这篇参考文献在说什么",
    "---",
    "",
    "Use this workflow when the user wants to verify a citation, related-work statement, or reference trail.",
    "",
    "1. Extract the exact local claim near the citation.",
    "2. Identify what kind of support is needed: fact, method precedent, benchmark, dataset, or broad motivation.",
    "3. Check whether the cited source appears to directly support that claim, partially support it, or merely sit nearby in the literature.",
    "4. Watch for citation drift: broad claims backed by narrow papers, outdated references, or references that only mention the topic in passing.",
    "5. Suggest the next reference to inspect if the current one is too weak.",
    "",
    "Keep the answer honest about what was verified locally versus what still requires opening the cited paper.",
  ].join("\n"),

  "structured-extraction": [
    "---",
    "name: Structured Extraction",
    "description: Convert a paper into a compact structured record for later comparison, notes, or retrieval.",
    "triggers:",
    "  - structured extraction",
    "  - extract fields",
    "  - reading note",
    "  - paper card",
    "  - 结构化提取",
    "  - 提取字段",
    "  - 阅读卡片",
    "---",
    "",
    "Use this workflow when the user wants a compact, reusable paper record instead of a free-form summary.",
    "",
    "1. Extract the minimum useful slots: task, setting, data, method, supervision, metrics, headline result, limitations, and evidence location.",
    "2. Prefer short field-value style output over long prose.",
    "3. Mark unknown or missing fields explicitly instead of guessing.",
    "4. Attach each important field to a section, page, table, or figure when possible.",
    "5. End with two or three comparison hooks that would help align this paper against others later.",
    "",
    "Optimize for reuse. The result should be easy to paste into a note, table, or literature tracker.",
  ].join("\n"),

  "research-gap-scan": [
    "---",
    "name: Research Gap Scan",
    "description: Identify plausible next questions, missing evidence, or underexplored directions around a paper.",
    "triggers:",
    "  - research gap",
    "  - future work",
    "  - open question",
    "  - what next",
    "  - 研究空白",
    "  - 后续方向",
    "  - 未来工作",
    "---",
    "",
    "Use this workflow when the user wants to know what is still missing or worth exploring next.",
    "",
    "1. Start from the paper's scope, assumptions, and strongest evidence.",
    "2. Identify boundaries the paper does not cover: datasets, settings, baselines, robustness checks, efficiency, or applicability.",
    "3. Separate easy follow-ups from real research gaps.",
    "4. Frame each candidate gap as a testable question, not a vague wish.",
    "5. End with the highest-value next reads or experiments that would validate the gap.",
    "",
    "Do not invent grand gaps from thin evidence. Small, concrete missing checks are often the most useful next step.",
  ].join("\n"),
};
