export const ANALYTICS_EVENTS = {
  aiSummaryBatchStarted: "ai_summary_batch_started",
  aiSummaryDeepRequested: "ai_summary_deep_requested",
  aiSummaryQuickRequested: "ai_summary_quick_requested",
  authCompleted: "auth_completed",
  authPageViewed: "auth_page_viewed",
  authVerificationCodeSent: "auth_verification_code_sent",
  chatCompleted: "chat_completed",
  chatModelSwitched: "chat_model_switched",
  chatPanelClosed: "chat_panel_closed",
  chatPanelOpened: "chat_panel_opened",
  chatSent: "chat_sent",
  paperChatModelRerouted: "paperchat_model_rerouted",
  paperChatQuotaError: "paperchat_quota_error",
  paperChatLowBalanceClicked: "paperchat_low_balance_clicked",
  paperChatPurchaseCompleted: "paperchat_purchase_completed",
  paperChatPurchaseDialogViewed: "paperchat_purchase_dialog_viewed",
  paperChatPurchaseEntryClicked: "paperchat_purchase_entry_clicked",
  paperChatPurchaseGrantFailed: "paperchat_purchase_grant_failed",
  paperChatPurchaseOrderCreateFailed: "paperchat_purchase_order_create_failed",
  paperChatPurchaseOrderCreateStarted:
    "paperchat_purchase_order_create_started",
  paperChatPurchaseOrderCreated: "paperchat_purchase_order_created",
  paperChatPurchasePaymentOpened: "paperchat_purchase_payment_opened",
  paperChatPurchaseProductSelected: "paperchat_purchase_product_selected",
  paperChatPurchaseTabSelected: "paperchat_purchase_tab_selected",
  paperChatPurchaseTimeout: "paperchat_purchase_timeout",
  paperChatRedeemCodeCompleted: "paperchat_redeem_code_completed",
  paperChatRedeemCodeSubmitted: "paperchat_redeem_code_submitted",
  pluginStarted: "plugin_started",
  settingsOpened: "settings_opened",
  settingsProviderViewed: "settings_provider_viewed",
  signInCompleted: "sign_in_completed",
} as const;

export type AnalyticsEventName =
  (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
